name: Deploy SpringBoot to EC2

on:
  push:
    branches:
      - release

env:
  S3_BUCKET_NAME: issuetracker-web
  RESOURCE_PATH: ./be/src/main/resources/application.yaml
  CODE_DEPLOY_APPLICATION_NAME: issue-tracker
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: issue-tracker

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11


        
      - name: make application.properties
        run:
          touch ./be/src/main/resources/application.yaml
        shell: bash
        
      - name: deliver application.properties
        run: echo "${{ secrets.DI_FROM_SECRET }}" > ./be/src/main/resources/application.yaml
        shell: bash
        
     
        
      - name: Grant execute permission for gradlew
        run: chmod +x ./be/gradlew
        shell: bash
        
      - name: Build with Gradle
        run: ./be/gradlew -p be build
        shell: bash
        
      - name: find
        run: find ./be/build
        shell: bash
    
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.AWS_REGION }} 


      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip


      - name: Code Deploy
        run: | 
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
